### PR TITLE
Human Coders & AFUP as MixIT13 partners

### PR DESCRIPTION
**Pull request by clacote**
(Agnes asked me to do it)

### CODE REVIEW

**Comment by clacote** [comment]
(when I think about refusing some smoothies for sponsors equality...)

**Comment by cexbrayat** [comment]
Wow! Not sure about that. We should have our real partners in there (cloudbees and supinfo) and maybe a "they talk about us" section with these ones (and a logo with tenth the size of the actual ones!).

**Comment by clacote** [comment]
@acrepet?

**Comment by acrepet** [comment]
en indiquant "ils nous soutiennent" plutot que partenaires ca me va... Ok pour reduire la taille des logos... Pas trop non plus...
on peut rajouter une section partenaires pour supinfo et cloudbees

**Pull request merged**
